# ---------------------------------------------------
# TASK: CLEANUP - Remove previous workspace files
# ---------------------------------------------------
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove-old-files
      image: alpine
      script: |
        rm -rf $(workspaces.source.path)/*

---
# ---------------------------------------------------
# TASK: ESLINT - Run code linting
# ---------------------------------------------------
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: eslint
spec:
  workspaces:
    - name: source
  steps:
    - name: run-eslint
      image: node:18
      workingDir: $(workspaces.source.path)
      script: |
        npm install
        npx eslint .

---
# ---------------------------------------------------
# TASK: RUN JEST TESTS - Execute unit tests using Jest
# ---------------------------------------------------
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-jest-tests
spec:
  params:
    - name: args
      type: string
      default: ""
  workspaces:
    - name: source
  steps:
    - name: run-jest
      image: node:18
      workingDir: $(workspaces.source.path)
      script: |
        npm install
        npx jest $(params.args)

---
# ---------------------------------------------------
# PIPELINE: CI/CD Pipeline
# ---------------------------------------------------
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  params:
    - name: build-image
      type: string
      default: image-registry.openshift-image-registry.svc:5000/sn_icr_namespace/tekton-lab:latest

  workspaces:
    - name: output

  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      runAfter:
        - cleanup
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: https://github.com/ibm-developer-skills-network/ttwst-jhxyb-ci-cd-pipeline_js
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: output

    - name: eslint
      runAfter:
        - git-clone
      taskRef:
        name: eslint
      workspaces:
        - name: source
          workspace: output

    - name: run-jest-tests
      runAfter:
        - eslint
      taskRef:
        name: run-jest-tests
      params:
        - name: args
          value: "--passWithNoTests"
      workspaces:
        - name: source
          workspace: output
